#!/usr/bin/env python3
"""Rebuild slideshow/slides.json from the pictures in the slideshow/ folder.

Every image in slideshow/ becomes one slide on the home page, in alphabetical
order. The caption is the file name without its extension; a leading number
such as "01 " or "02_" is used only for ordering and is not shown.

GitHub runs this for you automatically (see .github/workflows/slideshow.yml).
On your own computer, double-click update-slideshow.command (Mac) or run:
    python3 update_slideshow.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
FOLDER = os.path.join(HERE, "slideshow")
EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif")

def title_from(name):
    stem = os.path.splitext(name)[0]
    stem = re.sub(r"^\d+[\s._-]+", "", stem)   # drop ordering prefix
    return stem.replace("_", " ").strip()

files = sorted((f for f in os.listdir(FOLDER)
                if f.lower().endswith(EXTS) and not f.startswith(".")),
               key=str.lower)
slides = [{"file": f, "title": title_from(f)} for f in files]
with open(os.path.join(FOLDER, "slides.json"), "w", encoding="utf-8") as fh:
    json.dump(slides, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
# slides.js lets the slideshow work when index.html is opened straight from disk
with open(os.path.join(FOLDER, "slides.js"), "w", encoding="utf-8") as fh:
    fh.write("// Generated by update_slideshow.py - do not edit by hand.\n")
    fh.write("window.DI_SLIDES = " + json.dumps(slides, ensure_ascii=False, indent=2) + ";\n")
print(f"Slideshow updated: {len(slides)} pictures")
for s in slides:
    print("  -", s["title"])
