// Generated by update_slideshow.py - do not edit by hand.
window.DI_SLIDES = [
  {
    "file": "01 Bluebot swimming over a seagrass bed.jpg",
    "title": "Bluebot swimming over a seagrass bed"
  },
  {
    "file": "02 Robots in the field - rocky shallows.jpg",
    "title": "Robots in the field - rocky shallows"
  },
  {
    "file": "03 Field Research.jpg",
    "title": "Field Research"
  },
  {
    "file": "04 Mangrove field study.jpg",
    "title": "Mangrove field study"
  },
  {
    "file": "05 From fish schools to robot formations.jpg",
    "title": "From fish schools to robot formations"
  },
  {
    "file": "06 Diamond formation.jpg",
    "title": "Diamond formation"
  },
  {
    "file": "07 Robot view - fisheye camera and depth estimate.jpg",
    "title": "Robot view - fisheye camera and depth estimate"
  }
];
